### ISSUE TITLE
アプリのアイコン

### ISSUE THREAD

**Issue by kmdkuk** [team-x-fun/shiftend#116]
# 概要
* 
*

**Comment by WMKisaragi** [comment]
とりあえず直感で作ってみた．
アップデートもできるし，暫定版として使って良いかも？
[icon.zip](https://github.com/team-x-fun/shiftend/files/5370481/icon.zip)

![アプリアイコンメイン - 1024x1024](https://user-images.githubusercontent.com/28590006/95844795-4a666200-0d84-11eb-940e-b1a550cfa650.png)
![通知とアクティビティ - 01](https://user-images.githubusercontent.com/28590006/95844810-4e927f80-0d84-11eb-9064-ea4bc239fd8a.png)
![通知とアクティビティ - 03](https://user-images.githubusercontent.com/28590006/95844816-505c4300-0d84-11eb-9739-80fcf8538677.png)
